Music/MusicWebApp/Controllers/PlaylistController.cs
using BusinessLogic.Abstract;
using DomainModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace MusicWebApp.Controllers
{
    public class PlaylistController : Controller
    {
        private readonly IPlaylistBL _playlistBL;
        private readonly ISongBL _songBL;
        private readonly IPlaylistSongBL _playlistSongBL;
        public PlaylistController(IPlaylistBL playlistBL, ISongBL songB, IPlaylistSongBL playlistSongBL)
        {
            _playlistBL = playlistBL;
            _songBL = songB;
            _playlistSongBL = playlistSongBL;
        }

        public IActionResult Index()
        {
            List<Playlist> playlists = _playlistBL.Read();

            return View(playlists);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Playlist playlist)
        {
            if (ModelState.IsValid)
            {
                _playlistBL.Create(playlist);
            }
            else
                return View();

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int playlist_id)
        {
            Playlist playlist = _playlistBL.Read(playlist_id);

            return View(playlist);
        }

        [HttpPost]
        public IActionResult Edit(Playlist playlist)
        {
            if (ModelState.IsValid)
            {
                _playlistBL.Update(playlist);
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int playlist_id)
        {
            _playlistBL.Delete(playlist_id);

            return RedirectToAction("Index");
        }

        public IActionResult PlaylistSongs(int playlist_id)
        {
            ViewBag.PlaylistId = playlist_id;

            List<Song> songs = _playlistBL.PlaylistSongs(playlist_id);

            return View(songs);
        }

        public IActionResult AddLike(int song_id, int playlist_id)
        {
            _songBL.AddLike(song_id);

            return RedirectToAction("PlaylistSongs", new { playlist_id = playlist_id });
        }

        public IActionResult RemoveSongFromPlaylist(int song_id, int playlist_id)
        {
            _playlistSongBL.DeleteSongFromPlaylist(song_id);

            return RedirectToAction("PlaylistSongs", new { playlist_id = playlist_id });
        }
    }
}

Music/MusicWebApp/Controllers/StatisticsController.cs
using BusinessLogic.Abstract;
using DomainModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace MusicWebApp.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly IMusicTypeBL _musicTypeBL;
        private readonly IArtistBL _artistBL;
        public StatisticsController(IMusicTypeBL musicTypeBL, IArtistBL artistBL)
        {
            _musicTypeBL = musicTypeBL;
            _artistBL = artistBL;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SelectGenre()
        {
            List<MusicType> musicTypes = _musicTypeBL.Read();

            return View(musicTypes);
        }

        public IActionResult MostLikedPerGenre(string genre)
        {
            List<Song> mostLikedSongs = _musicTypeBL.MostLikedSongs(genre);

            return View(mostLikedSongs);
        }

        public IActionResult TopGenre()
        {
            List<MusicType> topGenre = _musicTypeBL.TopGenre();

            return View(topGenre);
        }

        public IActionResult TopArtists()
        {
            List<Artist> topArtists = _artistBL.TopArtists();

            return View(topArtists);
        }
    }
}

Music/MusicWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicWebApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MusicWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                    <ul class="navbar-nav flex-grow-1 justify-content-center">

                        <li class="nav-item">
                            <a class="nav-link text-dawhiterk" asp-area="" asp-controller="Playlist" asp-action="Index">My playlists</a>
                        </li>

                        
                        <li class="nav-item">
                            <a class="nav-link text-dawhiterk" asp-area="" asp-controller="Statistics" asp-action="Index">Statistics</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MusicWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>